### ISSUE TITLE
Plugin Causes all of Runelite to Crash

### ISSUE THREAD

**Issue by low-tide-joe** [Skretzo/runelite-plugins#46]
I tried to record my bossfight with sol heredit and as I started the bossfight all of runelite crashed because of this plugin ty

**Comment by Skretzo** [comment]
Ouch! You are probably running the game with either the GPU plugin or the 117HD plugin, and currently the video recorder plugin is sadly not quite compatible with those two (might be related to graphics card, not sure). This problem is quite hard to solve, so I don't think this will be fixed anytime soon. I would recommend you to instead use an external program to record videos, e.g. OBS, as that is probably a better solution in all sorts of ways.

**Comment by low-tide-joe** [comment]
Perhaps add that as a warning to anyone who tries to use it in conjunction with HD or GPU plugins?

**Comment by Skretzo** [comment]
Thank you for the suggestion. I have now added a one-time warning in the plugin side panel. It will be live in the client in a week or so once the plugin review is completed.
